// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleTaskManager.Data.Persistence;

namespace SimpleTaskManager.Data.Persistence.Migrations
{
    [DbContext(typeof(TaskManagerContext))]
    partial class TaskManagerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleTaskManager.Data.Entities.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssignedById")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CreatedAt = new DateTime(2020, 3, 27, 23, 9, 21, 806, DateTimeKind.Local).AddTicks(8810),
                            CreatedById = 1,
                            Description = "Description 1",
                            LastUpdated = new DateTime(2020, 3, 27, 23, 9, 21, 808, DateTimeKind.Local).AddTicks(64),
                            Priority = 2,
                            Status = 1,
                            Title = "Test 1"
                        },
                        new
                        {
                            TaskId = 2,
                            CreatedAt = new DateTime(2020, 3, 27, 23, 9, 21, 809, DateTimeKind.Local).AddTicks(4552),
                            CreatedById = 1,
                            Description = "Description 2",
                            LastUpdated = new DateTime(2020, 3, 27, 23, 9, 21, 809, DateTimeKind.Local).AddTicks(4581),
                            Priority = 2,
                            Status = 1,
                            Title = "Test 2"
                        },
                        new
                        {
                            TaskId = 3,
                            CreatedAt = new DateTime(2020, 3, 27, 23, 9, 21, 809, DateTimeKind.Local).AddTicks(4693),
                            CreatedById = 1,
                            Description = "Description 3",
                            LastUpdated = new DateTime(2020, 3, 27, 23, 9, 21, 809, DateTimeKind.Local).AddTicks(4695),
                            Priority = 2,
                            Status = 1,
                            Title = "Test 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
